
import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
  title: 'Sign in | Nextjs Login',
  description: 'Generated by create next app',
  icons: {
    icon: `${process.env.PUBLIC_URL}/clm/favicon.ico.png`,
  }
}

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <div style={{ position: 'absolute', top: 0, right: 0 }}>
      {children}
    </div>
  );
}
